### ISSUE TITLE
소개 페이지 오타 발견

### ISSUE THREAD

**Issue by H2SU** [s-owl/s-owl.github.io#1]
https://skhu-sss.github.io/about/

소모임 내부적으로는, 내부 컨퍼런스인 SSSCON 개최 *빛* 내부 해킹대회 개최, 각종 스터디와 프로젝트를 진행하고 있습니다.
빛 -> 및

**Comment by sukso96100** [comment]
@parksojeong <- 이 친구가 고쳐줄 겁니다.

**Comment by sukso96100** [comment]
@Parksojeongjeong <- 이 친구가 고쳐줄 겁니다.

**Comment by sukso96100** [comment]
수정되었습니다.
e0e37fe7a0d91c80a07f78914d82f29ffe06490b
