### ISSUE TITLE
메인 페이지 오타 발견

### ISSUE THREAD

**Issue by H2SU** [s-owl/s-owl.github.io#2]
https://skhu-sss.github.io/
SKHU Sensible *Secutiry*
Secutiry -> Security

**Comment by sukso96100** [comment]
@kms6190 <-이 친구가 고쳐줄 겁니다.

**Comment by junshoong** [comment]
미안하게도 제가 #4 를 통해서 수정을 해버렸습니다.

**Comment by sukso96100** [comment]
@kms6190 그럼 이친구는 걍 원래 과제 하는걸로
